version: '3'

volumes:
  task2_local_postgres_data: {}
  task2_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: task2_local_django
    container_name: task2_local_django
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    command: /start
    network_mode: host
